# Generated by Django 5.1.2 on 2024-11-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('image', models.ImageField(upload_to='fast-food/images', verbose_name='Ikonkasi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalaar',
                'db_table': 'Kategoriyalar',
                'managed': True,
            },
        ),
    ]
