# Generated by Django 5.1.2 on 2024-11-05 12:03

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaraunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Mahsulot nomi')),
                ('body', models.TextField(verbose_name="Mahsulot haqida ma'lumot")),
                ('price_type', models.CharField(choices=[("so'm", "so'm"), ('₽', '₽'), ('$', '$')], default="so'm", max_length=10)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='', verbose_name='Rasmi')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nashr qilingan vaqt')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaraunt.categorymodel', verbose_name='Kategoriyasi')),
            ],
            options={
                'verbose_name': 'Produktlar',
                'verbose_name_plural': 'Produktlar',
                'managed': True,
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
